In [1]:
import numpy as np
import cv2 as cv
import os
import math
import skimage
from scipy import ndimage
from skimage import io, util
from skimage.color import rgb2gray
import shapely
from shapely.geometry import LineString, Point
from sympy import Point, Line
from scipy.linalg import cholesky

In [185]:
!pip list --format=freeze > requirements.txt

In [2]:
data_path = os.path.join(os.path.dirname(os.path.abspath('Assignment3.ipynb')), 'laptop')
output_path = os.path.join(os.path.dirname(os.path.abspath(data_path)), 'output')
final_path = os.path.join(os.path.dirname(os.path.abspath(data_path)), 'final')

#number_files = len(os.listdir(data_path)) - 1

number_files = 5
files = []
output = []
for i in range(number_files):
    file_name = os.path.join(data_path, '%d' % (i + 1) + '.jpeg')
    files.append(file_name)

img1 = cv.imread(files[0])
shape = img1.shape
print(shape)

(960, 1280, 3)


In [150]:
size = 5
thresh = 0.135
power = []

output_no = 0
for file in files:
        
    img = cv.imread(file)
    shape = img.shape
    
    filtered = ndimage.gaussian_filter(img, sigma = 1.0)
    out = img.copy()
    gray = rgb2gray(filtered)
    gray = np.float32(gray)
    
    dest = cv.cornerHarris(gray, 2, 5, 0.07)
    dest = cv.dilate(dest, None)
    #out[dest > 0.01 * dest.max()] = [0, 0, 255]
    print(dest.shape)
    corners = []
    for i in range(shape[0]):
        for j in range(shape[1]):
            if dest[i][j] > 0.04 * dest.max():
                corners.append([i, j, dest[i][j]])
    
    sortedc = sorted(corners, key = lambda x : x[2], reverse = True)
    final = []
    final.append(sortedc[0][:-1])
    dis = 2 * size
    for i in sortedc :
        for j in final :
            if(abs(i[0] - j[0] <= dis) and abs(i[1] - j[1]) <= dis) :
                break
        else :
            final.append(i[:-1])
    power.append(final)        
    for el in final:
        out[el[0]][el[1]] = [255, 0, 0]
        cv.rectangle(out, (int(el[1] - 3), int(el[0] - 3)), (int(el[1] + 3), int(el[0] + 3)), (0, 255, 0), 4)
        cv.putText(out, '%d ,' %(el[1]) + '%d'  %(el[0]) , (int(el[1] - 3), int(el[0] - 3) - 10), cv.FONT_HERSHEY_SIMPLEX, 0.5, (36,255,12), 2)
    output_no += 1
    print("number of corner pixels: ", str(len(corners)))
    print("number of final corner pixels: ", str(len(final)))
    cv.imwrite(os.path.join(output_path, '%d' % output_no + '.jpg'), out)
    print("DONE ", str(output_no))

(960, 1280)
number of corner pixels:  2622
number of final corner pixels:  54
DONE  1
(960, 1280)
number of corner pixels:  2838
number of final corner pixels:  52
DONE  2
(960, 1280)
number of corner pixels:  2951
number of final corner pixels:  53
DONE  3
(960, 1280)
number of corner pixels:  2932
number of final corner pixels:  70
DONE  4
(960, 1280)
number of corner pixels:  2752
number of final corner pixels:  55
DONE  5


In [3]:
#image 1
#horizontal, vertical
poi = np.array([[0.0 for i in range(4)] for j in range(5)])

A = Point(437, 381)
B = Point(879, 429)

C = Point(395, 778)
D = Point(938, 797)

line1 = Line(A, B)
line2 = Line(C, D)

int_pt1 = line1.intersection(line2)
poi11 = int_pt1[0][0], int_pt1[0][1]

print(poi11)

E = Point(437, 381)
F = Point(395, 778)

G = Point(879, 429)
H = Point(938, 797)

line3 = Line(E, F)
line4 = Line(G, H)

int_pt2 = line3.intersection(line4)
poi12 = int_pt2[0][0], int_pt2[0][1]

print(poi12)
poi[0] = int_pt1[0][0], int_pt1[0][1], int_pt2[0][0], int_pt2[0][1]

(51677570/8833, 8558229/8833)
(23702731/38879, -48637229/38879)


In [4]:
#image 2
#horizontal, vertical

A = Point(306, 264)
B = Point(746, 309)

C = Point(263, 743)
D = Point(794, 739)

line1 = Line(A, B)
line2 = Line(C, D)

int_pt1 = line1.intersection(line2)
poi31 = int_pt1[0][0], int_pt1[0][1], 1

print(poi31)

E = Point(306, 264)
F = Point(263, 743)

G = Point(746, 309)
H = Point(794, 739)

line3 = Line(E, F)
line4 = Line(G, H)

int_pt2 = line3.intersection(line4)
poi32 = int_pt2[0][0], int_pt2[0][1], 1

print(poi32)
poi[1] = int_pt1[0][0], int_pt1[0][1], int_pt2[0][0], int_pt2[0][1]

(3419666/733, 520311/733, 1)
(1481158/2963, -5617208/2963, 1)


In [5]:
#image 3

A = Point(350, 179)
B = Point(834, 134)

C = Point(423, 772)
D = Point(863, 756)

line1 = Line(A, B)
line2 = Line(C, D)

int_pt1 = line1.intersection(line2)
poi51 = int_pt1[0][0], int_pt1[0][1], 1

print(poi51)

E = Point(350, 179)
F = Point(423, 772)

G = Point(834, 134)
H = Point(863, 756)

line3 = Line(E, F)
line4 = Line(G, H)

int_pt2 = line3.intersection(line4)
poi52 = int_pt2[0][0], int_pt2[0][1], 1

print(poi52)
poi[2] = int_pt1[0][0], int_pt1[0][1], int_pt2[0][0], int_pt2[0][1]

(-1393534/137, 1743998/1507, 1)
(31944919/28209, 184344740/28209, 1)


In [6]:
#image 4

A = Point(433, 210)
B = Point(963, 300)

C = Point(320, 637)
D = Point(862, 773)

line1 = Line(A, B)
line2 = Line(C, D)

int_pt1 = line1.intersection(line2)
poi41 = int_pt1[0][0], int_pt1[0][1], 1

print(poi41)

E = Point(433, 210)
F = Point(320, 637)

G = Point(963, 300)
H = Point(862, 773)

line3 = Line(E, F)
line4 = Line(G, H)

int_pt2 = line3.intersection(line4)
poi42 = int_pt2[0][0], int_pt2[0][1], 1

print(poi42)
poi[3] = int_pt1[0][0], int_pt1[0][1], int_pt2[0][0], int_pt2[0][1]

(-6035808/1165, -865959/1165, 1)
(16912283/5161, -54379220/5161, 1)


In [7]:
#image 5

A = Point(426, 401)
B = Point(934, 401)

C = Point(403, 714)
D = Point(876, 658)

line1 = Line(A, B)
line2 = Line(C, D)

int_pt1 = line1.intersection(line2)
poi21 = int_pt1[0][0], int_pt1[0][1], 1

print(poi21)

E = Point(426, 401)
F = Point(403, 714)

G = Point(934, 401)
H = Point(876, 658)

line3 = Line(E, F)
line4 = Line(G, H)

int_pt2 = line3.intersection(line4)
poi22 = int_pt2[0][0], int_pt2[0][1], 1

print(poi22)
poi[4] = int_pt1[0][0], int_pt1[0][1], int_pt2[0][0], int_pt2[0][1]

print(poi)

(170617/56, 401, 1)
(2212730/12243, 45773471/12243, 1)
[[  5850.51171742    968.8926752     609.6538234   -1250.98971167]
 [  4665.30150068    709.83765348    499.88457644  -1895.7840027 ]
 [-10171.7810219    1157.26476443   1132.43712999   6534.96189159]
 [ -5180.95107296   -743.31244635   3276.93915908 -10536.56655687]
 [  3046.73214286    401.            180.73429715   3738.74630401]]


In [8]:
poi = poi / 1000
arr1 = np.array([[0.0 for i in range(5)] for j in range(5)])
arr2 = np.array([-1.0 for i in range(5)])
for i in range(5):
    temp = poi[i]
    arr1[i] = temp[0]*temp[2], temp[0]*temp[3]+temp[1]*temp[2], temp[0]+temp[2], temp[1]*temp[3], temp[1]+temp[3]
soln = np.linalg.solve(arr1, arr2)
W = np.array([[soln[0], soln[1], soln[2]], [soln[1], soln[3], soln[4]], [soln[2], soln[4], 1]])
Winv = np.linalg.inv(W)
K = cholesky(Winv)
print(K)

[[1.74822648 0.30040889 0.63326311]
 [0.         1.64155325 0.34782767]
 [0.         0.         1.        ]]


In [12]:
Kinv = np.linalg.inv(K)
w = np.array([
    [1, 0, 1, 2, 1, 1, 1, 5, 5],
    [0, 1, 1, 1, 2, 3, 4, 1, 2],
    np.zeros(9), np.ones(9)
    ])
m = np.array([
    [452, 365, 441, 523, 437, 428, 423, 737, 738],
    [263, 311, 317, 330, 381, 445, 518, 358, 413], 
    np.ones(9)
    ])
m[0] = m[0] / 1000
m[1] = m[1] / 1000

RTfit, _, _, _ = np.linalg.lstsq(w.T, (Kinv @ m).T, rcond=None)
Rfit = np.around(RTfit.T, 6)
print(Rfit)
print(Rfit.shape)

[[ 0.041889 -0.01054   0.       -0.137379]
 [ 0.005037  0.038684  0.       -0.060075]
 [-0.       -0.        0.        1.      ]]
(3, 4)


In [13]:
img = cv.imread(files[0])
point1 = np.matmul(np.matmul(K, Rfit), [0, 0, 0, 1])
point2 = np.matmul(np.matmul(K, Rfit), [1, 0, 0, 1])
point3 = np.matmul(np.matmul(K, Rfit), [0, 1, 0, 1])
point4 = np.matmul(np.matmul(K, Rfit), [1, 1, 0, 1])

cv.rectangle(img, (int(point1[0] - 3), int(point1[1] - 3)), (int(point1[0] + 3), int(point1[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point2[0] - 3), int(point2[1] - 3)), (int(point2[0] + 3), int(point2[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point3[0] - 3), int(point3[1] - 3)), (int(point3[0] + 3), int(point3[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point4[0] - 3), int(point4[1] - 3)), (int(point4[0] + 3), int(point4[1] + 3)), (0, 255, 0), 4)

point5 = np.matmul(np.matmul(K, Rfit), [0, 0, 1, 1])
point6 = np.matmul(np.matmul(K, Rfit), [1, 0, 1, 1])
point7 = np.matmul(np.matmul(K, Rfit), [0, 1, 1, 1])
point8 = np.matmul(np.matmul(K, Rfit), [1, 1, 1, 1])

cv.rectangle(img, (int(point5[0] - 3), int(point5[1] - 3)), (int(point5[0] + 3), int(point5[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point6[0] - 3), int(point6[1] - 3)), (int(point6[0] + 3), int(point6[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point7[0] - 3), int(point7[1] - 3)), (int(point7[0] + 3), int(point7[1] + 3)), (0, 255, 0), 4)
cv.rectangle(img, (int(point8[0] - 3), int(point8[1] - 3)), (int(point8[0] + 3), int(point8[1] + 3)), (0, 255, 0), 4)

cv.imwrite(os.path.join(final_path, '1.jpg'), img)

True